"""empty message

Revision ID: 04e0ea81a414
Revises: 89e83b00f8db
Create Date: 2021-11-09 20:56:27.101581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e0ea81a414'
down_revision = '89e83b00f8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
