"""empty message

Revision ID: 0bcd1f606e4d
Revises: 8c39fd73bc74
Create Date: 2021-11-12 00:08:05.473963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcd1f606e4d'
down_revision = '8c39fd73bc74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('due_date', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'due_date')
    # ### end Alembic commands ###
