"""empty message

Revision ID: 0d6e41cdb709
Revises: 177a1918ae8d
Create Date: 2021-11-10 21:38:49.344562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6e41cdb709'
down_revision = '177a1918ae8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'video', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='unique')
    # ### end Alembic commands ###
