"""Added rental model

Revision ID: 11009e88f452
Revises: 19a71d9a583a
Create Date: 2021-11-12 09:23:52.091930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11009e88f452'
down_revision = '19a71d9a583a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('videos_checked_out', sa.Integer(), nullable=True))
    op.drop_column('customer', 'phone_number')
    op.drop_column('customer', 'id')
    op.add_column('rental', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('rental', sa.Column('due_date', sa.DateTime(), nullable=False))
    op.add_column('rental', sa.Column('video_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['customer_id'])
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_column('rental', 'video_id')
    op.drop_column('rental', 'due_date')
    op.drop_column('rental', 'customer_id')
    op.add_column('customer', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'videos_checked_out')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###
