"""empty message

Revision ID: 15809d1ef81a
Revises: 06b66d485db9
Create Date: 2021-11-12 13:25:51.117365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15809d1ef81a'
down_revision = '06b66d485db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_out', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checked_out')
    # ### end Alembic commands ###
