"""Added Customer Model

Revision ID: 19a71d9a583a
Revises: d15d80739e3b
Create Date: 2021-11-07 22:53:26.753046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a71d9a583a'
down_revision = 'd15d80739e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('register_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'register_at')
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'phone_number')
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###
