"""empty message

Revision ID: 19bbd6a7bcfc
Revises: 0383e62e9601
Create Date: 2021-11-12 10:40:54.723993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bbd6a7bcfc'
down_revision = '0383e62e9601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('is_checked_in', sa.Boolean(), nullable=True))
    op.drop_column('rental', 'available_inventory')
    op.drop_column('rental', 'videos_checked_out_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('videos_checked_out_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rental', sa.Column('available_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rental', 'is_checked_in')
    # ### end Alembic commands ###
