"""fixed naming in customer model

Revision ID: 1a9a78475cfc
Revises: e62f2a25c50d
Create Date: 2021-11-08 12:25:48.769455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9a78475cfc'
down_revision = 'e62f2a25c50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('post_code', sa.Integer(), nullable=True))
    op.drop_column('customer', 'postcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('postcode', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'post_code')
    # ### end Alembic commands ###
