"""empty message

Revision ID: 20f1eeb5e93d
Revises: da9f1ade6848
Create Date: 2021-11-11 13:21:43.643149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f1eeb5e93d'
down_revision = 'da9f1ade6848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('customer', 'phone_number')
    op.drop_column('customer', 'customer_id')
    op.add_column('video', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('video', 'video_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('video', 'id')
    op.add_column('customer', sa.Column('customer_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'id')
    # ### end Alembic commands ###
