"""empty message

Revision ID: 2136e773d8d8
Revises: f0f2716e4764
Create Date: 2021-11-10 16:52:35.858902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2136e773d8d8'
down_revision = 'f0f2716e4764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('register_at', sa.DateTime(), nullable=True))
    op.add_column('rental', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('rental', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('rental', sa.Column('return_date', sa.DateTime(), nullable=True))
    op.add_column('rental', sa.Column('video_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['id'])
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['id'])
    op.drop_column('rental', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_column('rental', 'video_id')
    op.drop_column('rental', 'return_date')
    op.drop_column('rental', 'due_date')
    op.drop_column('rental', 'customer_id')
    op.drop_column('customer', 'register_at')
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###
