"""empty message

Revision ID: 2142a89574aa
Revises: c2961079493d
Create Date: 2021-11-14 14:28:38.583618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2142a89574aa'
down_revision = 'c2961079493d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('video', 'video_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('video', 'id')
    # ### end Alembic commands ###
