"""empty message

Revision ID: 222ca5b8a33d
Revises: 7669fe2b97c1
Create Date: 2021-11-11 11:25:18.247771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '222ca5b8a33d'
down_revision = '7669fe2b97c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.drop_column('customer', 'register_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('register_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'registered_at')
    # ### end Alembic commands ###
