"""empty message

Revision ID: 234d15c968be
Revises: f760723813f2
Create Date: 2021-11-08 20:13:58.116879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234d15c968be'
down_revision = 'f760723813f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_column('customer', 'id')
    op.add_column('video', sa.Column('video_id', sa.Integer(), nullable=False))
    op.drop_column('video', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('video', 'video_id')
    op.add_column('customer', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###
