"""empty message

Revision ID: 270b043ade4e
Revises: 692764bb0bb4
Create Date: 2021-11-09 11:14:55.301945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270b043ade4e'
down_revision = '692764bb0bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
