"""empty message

Revision ID: 275263c0260f
Revises: 2e8ee0672b15
Create Date: 2021-11-08 18:12:45.716636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275263c0260f'
down_revision = '2e8ee0672b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
