"""empty message

Revision ID: 27a6f0d99e8d
Revises: 0d6e41cdb709
Create Date: 2021-11-11 10:24:47.185849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a6f0d99e8d'
down_revision = '0d6e41cdb709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rentals', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rentals', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rentals', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rentals', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
