"""empty message

Revision ID: 27ca9680ef7b
Revises: 7fac3bb913d3
Create Date: 2021-11-05 12:46:25.053957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ca9680ef7b'
down_revision = '7fac3bb913d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('postal_code', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.add_column('rental', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('rental', sa.Column('title', sa.String(), nullable=True))
    op.add_column('rental', sa.Column('total_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'total_inventory')
    op.drop_column('rental', 'title')
    op.drop_column('rental', 'release_date')
    op.drop_column('customer', 'registered_at')
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###
