"""empty message

Revision ID: 2c6ae8584941
Revises: 352c0aea8cd6
Create Date: 2021-11-13 14:26:59.802868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6ae8584941'
down_revision = '352c0aea8cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_out', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checked_out')
    # ### end Alembic commands ###
