"""empty message

Revision ID: 2d2b11291d4b
Revises: 787ca182a59b
Create Date: 2021-11-10 22:55:46.548055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2b11291d4b'
down_revision = '787ca182a59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('total_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'total_inventory')
    # ### end Alembic commands ###
