"""empty message

Revision ID: 2ff39e9960b6
Revises: 788dc83797fd
Create Date: 2021-11-09 15:44:46.667760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff39e9960b6'
down_revision = '788dc83797fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_column('customer', 'id')
    op.add_column('video', sa.Column('video_id', sa.Integer(), nullable=False))
    op.drop_column('video', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('video', 'video_id')
    op.add_column('customer', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###
