"""empty message

Revision ID: 3155b60d8508
Revises: 6733cdf6890c
Create Date: 2021-11-08 11:45:49.675660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3155b60d8508'
down_revision = '6733cdf6890c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('postal_code', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('registered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'registered_at')
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'phone_number')
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###
