"""empty message

Revision ID: 36507d70c6bf
Revises: 20f1eeb5e93d
Create Date: 2021-11-16 14:11:31.307562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36507d70c6bf'
down_revision = '20f1eeb5e93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('available_inventory', sa.Integer(), nullable=True))
    op.add_column('rental', sa.Column('checked_out', sa.Integer(), nullable=True))
    op.add_column('rental', sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=True))
    op.add_column('rental', sa.Column('due_date', sa.String(), nullable=True))
    op.add_column('rental', sa.Column('video_id', sa.Integer(), autoincrement=True, nullable=True))
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_column('rental', 'video_id')
    op.drop_column('rental', 'due_date')
    op.drop_column('rental', 'customer_id')
    op.drop_column('rental', 'checked_out')
    op.drop_column('rental', 'available_inventory')
    # ### end Alembic commands ###
