"""empty message

Revision ID: 378d4c73cb10
Revises: 55a721ad32c8
Create Date: 2021-11-08 11:03:27.066484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '378d4c73cb10'
down_revision = '55a721ad32c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.drop_column('video', 'release')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('release', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('video', 'release_date')
    # ### end Alembic commands ###
