"""empty message

Revision ID: 38469ed74615
Revises: defd44b0e096
Create Date: 2021-11-15 13:40:12.569481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38469ed74615'
down_revision = 'defd44b0e096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('videos_checked_in', sa.Boolean(), nullable=True))
    op.alter_column('rental', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rental', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rental', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rental', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rental', 'videos_checked_in')
    # ### end Alembic commands ###
