"""empty message

Revision ID: 3a8a88e4acf9
Revises: 73f1ff2b2465
Create Date: 2021-11-10 14:19:51.618327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8a88e4acf9'
down_revision = '73f1ff2b2465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('rental', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('rental', sa.Column('rental_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('rental', sa.Column('video_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['video_id'])
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['customer_id'])
    op.drop_column('rental', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_column('rental', 'video_id')
    op.drop_column('rental', 'rental_id')
    op.drop_column('rental', 'customer_id')
    op.alter_column('customer', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
