"""fixed naming in customer model

Revision ID: 3b72f000ccdb
Revises: 1a9a78475cfc
Create Date: 2021-11-08 12:27:25.613896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b72f000ccdb'
down_revision = '1a9a78475cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('postal_code', sa.Integer(), nullable=True))
    op.drop_column('customer', 'post_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('post_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'postal_code')
    # ### end Alembic commands ###
