"""empty message

Revision ID: 41663fa2d0c6
Revises: 9fe184d7f42a
Create Date: 2021-11-11 16:22:36.089865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41663fa2d0c6'
down_revision = '9fe184d7f42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id', 'video_id', 'customer_id')
    )
    op.drop_table('rental')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='rental_customer_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name='rental_video_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'video_id', 'customer_id', name='rental_pkey')
    )
    op.drop_table('video_rentals')
    # ### end Alembic commands ###
