"""empty message

Revision ID: 4cf1cbaa3c14
Revises: 31154e14c7e8
Create Date: 2021-11-14 09:35:12.855586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf1cbaa3c14'
down_revision = '31154e14c7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('customer', sa.Column('customer_registration', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('name', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('postal_code', sa.Integer(), nullable=True))
    op.drop_column('customer', 'id')
    op.add_column('rental', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('rental', sa.Column('description', sa.String(), nullable=True))
    op.add_column('rental', sa.Column('rental_id', sa.Integer(), nullable=False))
    op.add_column('rental', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('rental', 'id')
    op.add_column('video', sa.Column('release_date', sa.String(), nullable=True))
    op.add_column('video', sa.Column('total_inventory', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('video_id', sa.Integer(), nullable=False))
    op.add_column('video', sa.Column('video_title', sa.String(), nullable=True))
    op.drop_column('video', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('video', 'video_title')
    op.drop_column('video', 'video_id')
    op.drop_column('video', 'total_inventory')
    op.drop_column('video', 'release_date')
    op.add_column('rental', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('rental', 'title')
    op.drop_column('rental', 'rental_id')
    op.drop_column('rental', 'description')
    op.drop_column('rental', 'completed_at')
    op.add_column('customer', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'name')
    op.drop_column('customer', 'customer_registration')
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###
