"""empty message

Revision ID: 55a721ad32c8
Revises: 68a7bd8f1ac2
Create Date: 2021-11-08 11:01:07.677044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a721ad32c8'
down_revision = '68a7bd8f1ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('copies', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('release', sa.DateTime(), nullable=True))
    op.add_column('video', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'title')
    op.drop_column('video', 'release')
    op.drop_column('video', 'copies')
    # ### end Alembic commands ###
