"""empty message

Revision ID: 5ec298dbb464
Revises: 
Create Date: 2021-11-17 10:33:45.025587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec298dbb464'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('register_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('video', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('video', 'video_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('video', 'id')
    op.drop_table('customer')
    # ### end Alembic commands ###
