"""empty message

Revision ID: 73f1ff2b2465
Revises: 4f20ffbd5e7f
Create Date: 2021-11-08 16:29:25.413535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f1ff2b2465'
down_revision = '4f20ffbd5e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
