"""empty message

Revision ID: 75b4d30dfcfe
Revises: 035ded97b73f
Create Date: 2021-11-12 16:35:09.725511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b4d30dfcfe'
down_revision = '035ded97b73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_out', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checked_out')
    # ### end Alembic commands ###
