"""empty message

Revision ID: 783890a21d88
Revises: 03d6423a1d16
Create Date: 2021-11-07 17:08:56.376838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783890a21d88'
down_revision = '03d6423a1d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
