"""empty message

Revision ID: 788dc83797fd
Revises: 4ea3b4f4b1ca
Create Date: 2021-11-09 15:06:25.241825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788dc83797fd'
down_revision = '4ea3b4f4b1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
