"""empty message

Revision ID: 8789bf14c06a
Revises: 4cf1cbaa3c14
Create Date: 2021-11-14 14:15:10.361078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8789bf14c06a'
down_revision = '4cf1cbaa3c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_inventory', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('video_release_date', sa.String(), nullable=True))
    op.drop_column('video', 'total_inventory')
    op.drop_column('video', 'release_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('release_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('total_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('video', 'video_release_date')
    op.drop_column('video', 'video_inventory')
    # ### end Alembic commands ###
