"""empty message

Revision ID: 89e83b00f8db
Revises: 0c412d627e97
Create Date: 2021-11-09 20:13:38.932357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e83b00f8db'
down_revision = '0c412d627e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'videos_checked_out_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('videos', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customers', 'videos_checked_out_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
