"""empty message

Revision ID: 8b840482f57c
Revises: 0f51ba93390d
Create Date: 2021-11-11 09:36:24.165179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b840482f57c'
down_revision = '0f51ba93390d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('rental', sa.Column('video_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['id'])
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_column('rental', 'video_id')
    op.drop_column('rental', 'customer_id')
    # ### end Alembic commands ###
