"""empty message

Revision ID: 8c39fd73bc74
Revises: 66630100c474
Create Date: 2021-11-12 00:04:55.122589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c39fd73bc74'
down_revision = '66630100c474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'due_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('due_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
