"""empty message

Revision ID: 9aa9b3b4a5bc
Revises: 1f940af2691d
Create Date: 2021-11-06 19:16:43.698848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa9b3b4a5bc'
down_revision = '1f940af2691d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('register_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'register_at')
    # ### end Alembic commands ###
