"""empty message

Revision ID: 9f27d693475e
Revises: 8b840482f57c
Create Date: 2021-11-12 16:10:16.351412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f27d693475e'
down_revision = '8b840482f57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checkout_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checkout_date')
    # ### end Alembic commands ###
