"""empty message

Revision ID: c22a6a90c351
Revises: 0c96d53ae30c
Create Date: 2021-11-11 15:19:03.272421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22a6a90c351'
down_revision = '0c96d53ae30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rental_customer_id_fkey', 'rental', type_='foreignkey')
    op.drop_constraint('rental_video_id_fkey', 'rental', type_='foreignkey')
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.create_foreign_key('rental_video_id_fkey', 'rental', 'video', ['video_id'], ['id'])
    op.create_foreign_key('rental_customer_id_fkey', 'rental', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###
