"""empty message

Revision ID: c2961079493d
Revises: 8789bf14c06a
Create Date: 2021-11-14 14:23:41.220069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2961079493d'
down_revision = '8789bf14c06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('inventory', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('release_date', sa.String(), nullable=True))
    op.add_column('video', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('video', 'video_inventory')
    op.drop_column('video', 'video_release_date')
    op.drop_column('video', 'video_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('video_release_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('video_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('video', 'title')
    op.drop_column('video', 'release_date')
    op.drop_column('video', 'inventory')
    # ### end Alembic commands ###
