"""empty message

Revision ID: c4d4e759f71a
Revises: 4acd7f0603c6
Create Date: 2021-11-09 18:37:39.806291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d4e759f71a'
down_revision = '4acd7f0603c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', sa.String(), nullable=False))
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('customer', sa.Column('postal_code', sa.String(), nullable=False))
    op.add_column('customer', sa.Column('register_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'register_at')
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###
