"""empty message

Revision ID: c6116831c617
Revises: 2136e773d8d8
Create Date: 2021-11-11 10:17:36.447800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6116831c617'
down_revision = '2136e773d8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'id')
    # ### end Alembic commands ###
