"""empty message

Revision ID: cc23691943b8
Revises: a1aa78b796c1
Create Date: 2021-11-14 14:25:49.584153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc23691943b8'
down_revision = 'a1aa78b796c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_out', sa.Boolean(), nullable=True))
    op.add_column('rental', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'due_date')
    op.drop_column('rental', 'checked_out')
    # ### end Alembic commands ###
