"""empty message

Revision ID: d2ce71a74bfd
Revises: c22a6a90c351
Create Date: 2021-11-14 09:14:45.750737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ce71a74bfd'
down_revision = 'c22a6a90c351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checkout_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checkout_date')
    # ### end Alembic commands ###
