"""empty message

Revision ID: d9d67bc964b2
Revises: 3a8a88e4acf9
Create Date: 2021-11-10 14:39:04.447629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d67bc964b2'
down_revision = '3a8a88e4acf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'due_date')
    # ### end Alembic commands ###
