"""add datetime default

Revision ID: e62f2a25c50d
Revises: fb9d6256dc1d
Create Date: 2021-11-08 11:54:20.175208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62f2a25c50d'
down_revision = 'fb9d6256dc1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('inventory', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('video', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'title')
    op.drop_column('video', 'release_date')
    op.drop_column('video', 'inventory')
    # ### end Alembic commands ###
