"""some rearrangement in the rental model

Revision ID: e95cbb86183b
Revises: 7acac6094004
Create Date: 2021-11-15 11:39:21.881355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e95cbb86183b'
down_revision = '7acac6094004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('rental_date', sa.DateTime(), nullable=True))
    op.drop_column('rental', 'due_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('rental', 'rental_date')
    # ### end Alembic commands ###
