"""empty message

Revision ID: f71d63741ed2
Revises: 2142a89574aa
Create Date: 2021-11-14 14:29:09.388673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71d63741ed2'
down_revision = '2142a89574aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_id', sa.Integer(), nullable=False))
    op.drop_column('video', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('video', 'video_id')
    # ### end Alembic commands ###
