"""empty message

Revision ID: fc30d9ac2258
Revises: 9aa9b3b4a5bc
Create Date: 2021-11-07 10:35:36.479221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc30d9ac2258'
down_revision = '9aa9b3b4a5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_column('customer', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###
