"""empty message

Revision ID: fcfd77666854
Revises: 696c63b7fc73
Create Date: 2021-11-14 15:16:00.860031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfd77666854'
down_revision = '696c63b7fc73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('customer', 'id')
    # ### end Alembic commands ###
