"""empty message

Revision ID: fde5053deeaa
Revises: 139832649b33
Create Date: 2021-11-08 11:34:32.707527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde5053deeaa'
down_revision = '139832649b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=False))
    op.drop_column('customer', 'phone_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_num', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
